`timescale 1ns/1ps

module tb_TX;

    // Fast simulation configuration:
    // 100 MHz / 10 MHz = exactly 10 clocks per UART bit.
    localparam integer CLK_FREQ_HZ          = 100_000_000;
    localparam integer BAUD_RATE            = 10_000_000;
    localparam integer EXPECTED_CLKS_PER_BIT = 10;
    localparam integer CLK_PERIOD_NS         = 10;

    logic       clk;
    logic       rst_n;
    logic [7:0] tx_data;
    logic       tx_start;

    wire        tx_serial;
    wire        tx_busy;
    wire        tx_done;

    integer checks;
    integer errors;
    integer accepted_transactions;

    logic previous_done;

    // Portable manual functional-coverage flags.
    bit seen_zero;
    bit seen_all_ones;
    bit seen_alternating;
    bit seen_other;
    bit seen_parity_zero;
    bit seen_parity_one;
    bit seen_start_while_busy;
    bit seen_data_change_while_busy;
    bit seen_back_to_back;
    bit seen_reset_while_busy;

    //============================================================
    // DUT
    //============================================================

    TX #(
        .CLK_FREQ_HZ (CLK_FREQ_HZ),
        .BAUD_RATE   (BAUD_RATE)
    ) dut (
        .clk       (clk),
        .rst_n     (rst_n),
        .tx_data   (tx_data),
        .tx_start  (tx_start),
        .tx_serial (tx_serial),
        .tx_busy   (tx_busy),
        .tx_done   (tx_done)
    );

    // 100 MHz simulation clock.
    initial clk = 1'b0;

    always #(CLK_PERIOD_NS / 2)
        clk = ~clk;

    //============================================================
    // Basic assertion helper
    //============================================================

    task automatic check(
        input logic  condition,
        input string message
    );
        begin
            checks = checks + 1;

            assert (condition === 1'b1)
            else begin
                errors = errors + 1;
                $error("[%0t] CHECK FAILED: %s", $time, message);
            end
        end
    endtask

    //============================================================
    // Continuous procedural assertions
    //
    // These work with simulators such as Icarus Verilog.
    // Sampling at the falling edge avoids racing the DUT, which
    // updates its registers at the rising edge.
    //============================================================

    always @(negedge clk) begin
        if (!rst_n) begin
            previous_done = 1'b0;
        end
        else begin
            check(
                !$isunknown({tx_serial, tx_busy, tx_done}),
                "TX outputs must never contain X or Z"
            );

            if (!tx_busy) begin
                check(
                    tx_serial === 1'b1,
                    "TX serial line must be high while not busy"
                );
            end

            if (tx_done) begin
                check(
                    !tx_busy,
                    "tx_done must not be high while tx_busy is high"
                );

                check(
                    tx_serial === 1'b1,
                    "Serial line must be high when transmission completes"
                );
            end

            if (previous_done) begin
                check(
                    tx_done === 1'b0,
                    "tx_done must last for exactly one clock"
                );
            end

            previous_done = tx_done;
        end
    end

    //============================================================
    // Coverage sampling
    //============================================================

    task automatic sample_accepted_data(input logic [7:0] data);
        begin
            accepted_transactions = accepted_transactions + 1;

            case (data)
                8'h00: seen_zero        = 1'b1;
                8'hFF: seen_all_ones    = 1'b1;
                8'h55,
                8'hAA: seen_alternating = 1'b1;
                default: seen_other     = 1'b1;
            endcase

            // ^data is the even-parity bit generated by the DUT.
            if (^data)
                seen_parity_one = 1'b1;
            else
                seen_parity_zero = 1'b1;
        end
    endtask

    //============================================================
    // Reset
    //============================================================

    task automatic reset_dut;
        begin
            $display("[%0t] Applying reset", $time);

            rst_n    = 1'b0;
            tx_start = 1'b0;
            tx_data  = 8'h00;

            repeat (3)
                @(posedge clk);

            @(negedge clk);

            check(tx_serial === 1'b1,
                  "tx_serial must be high during reset");

            check(tx_busy === 1'b0,
                  "tx_busy must be low during reset");

            check(tx_done === 1'b0,
                  "tx_done must be low during reset");

            rst_n = 1'b1;

            @(posedge clk);
            @(negedge clk);

            check(tx_serial === 1'b1,
                  "tx_serial must remain high after reset");

            check(tx_busy === 1'b0,
                  "TX must be idle after reset");

            check(tx_done === 1'b0,
                  "tx_done must remain low after reset");
        end
    endtask

    //============================================================
    // Send one legal TX request
    //============================================================

    task automatic start_frame(input logic [7:0] data);
        begin
            // Drive inputs on the falling edge so they are stable
            // before the DUT samples them on the next rising edge.
            @(negedge clk);

            check(tx_busy === 1'b0,
                  "A normal request must begin while TX is idle");

            tx_data  = data;
            tx_start = 1'b1;

            // The request is accepted at the rising edge between
            // these two falling edges.
            @(negedge clk);

            tx_start = 1'b0;

            sample_accepted_data(data);

            check(tx_busy === 1'b1,
                  "tx_busy must rise after an accepted request");

            check(tx_serial === 1'b0,
                  "The start bit must begin after an accepted request");

            check(tx_done === 1'b0,
                  "tx_done must remain low at the start of a frame");
        end
    endtask

    //============================================================
    // Verify one UART symbol
    //
    // A symbol is one start, data, parity, or stop bit.
    // This checks the value during every clock of the symbol.
    //============================================================

    task automatic expect_symbol(
        input logic  expected_value,
        input string symbol_name
    );
        begin
            for (integer cycle = 0;
                 cycle < EXPECTED_CLKS_PER_BIT;
                 cycle = cycle + 1) begin

                check(
                    tx_serial === expected_value,
                    $sformatf(
                        "%s: expected tx_serial=%0b during clock %0d/%0d",
                        symbol_name,
                        expected_value,
                        cycle + 1,
                        EXPECTED_CLKS_PER_BIT
                    )
                );

                check(
                    tx_busy === 1'b1,
                    $sformatf(
                        "%s: tx_busy dropped before the frame finished",
                        symbol_name
                    )
                );

                check(
                    tx_done === 1'b0,
                    $sformatf(
                        "%s: tx_done rose before the stop bit finished",
                        symbol_name
                    )
                );

                if (cycle != EXPECTED_CLKS_PER_BIT - 1)
                    @(negedge clk);
            end

            // Advance to the first falling edge of the next symbol.
            @(negedge clk);
        end
    endtask

    //============================================================
    // Verify all symbols in one frame
    //============================================================

    task automatic expect_frame_symbols(
        input logic [7:0] data,
        input string      test_name
    );
        begin
            // Start bit
            expect_symbol(
                1'b0,
                $sformatf("%s start bit", test_name)
            );

            // UART sends the least-significant bit first.
            for (integer bit_number = 0;
                 bit_number < 8;
                 bit_number = bit_number + 1) begin

                expect_symbol(
                    data[bit_number],
                    $sformatf(
                        "%s data bit %0d",
                        test_name,
                        bit_number
                    )
                );
            end

            // Even parity: ^data is chosen so the total number of
            // ones across data and parity is even.
            expect_symbol(
                ^data,
                $sformatf("%s parity bit", test_name)
            );

            // Stop bit
            expect_symbol(
                1'b1,
                $sformatf("%s stop bit", test_name)
            );
        end
    endtask

    //============================================================
    // Verify completion behavior
    //============================================================

    task automatic check_completion(input string test_name);
        begin
            // We arrive here at the first falling edge after the
            // stop bit has completed.
            check(
                tx_busy === 1'b0,
                $sformatf("%s: tx_busy did not clear", test_name)
            );

            check(
                tx_done === 1'b1,
                $sformatf("%s: tx_done did not pulse", test_name)
            );

            check(
                tx_serial === 1'b1,
                $sformatf("%s: serial line is not idle after frame", test_name)
            );

            // tx_done must clear after one clock.
            @(negedge clk);

            check(
                tx_done === 1'b0,
                $sformatf("%s: tx_done lasted longer than one clock", test_name)
            );

            check(
                tx_busy === 1'b0,
                $sformatf("%s: TX did not remain idle", test_name)
            );
        end
    endtask

    //============================================================
    // Complete normal-frame test
    //============================================================

    task automatic run_frame(
        input logic [7:0] data,
        input string      test_name
    );
        begin
            $display(
                "[%0t] Testing %s with data 0x%02h",
                $time,
                test_name,
                data
            );

            start_frame(data);
            expect_frame_symbols(data, test_name);
            check_completion(test_name);
        end
    endtask

    //============================================================
    // Request while busy test
    //
    // The second request must be ignored. Changing tx_data must
    // also not corrupt the byte already stored in tx_buffer.
    //============================================================

    task automatic test_request_while_busy;
        logic [7:0] original_data;
        begin
            original_data = 8'h96;

            $display("[%0t] Testing request while busy", $time);

            start_frame(original_data);

            fork
                begin : monitor_original_frame
                    expect_frame_symbols(
                        original_data,
                        "request-while-busy"
                    );
                end

                begin : inject_illegal_request
                    // Wait until partway through the data bits.
                    repeat (EXPECTED_CLKS_PER_BIT * 3)
                        @(negedge clk);

                    check(
                        tx_busy === 1'b1,
                        "TX must be busy before injecting the second request"
                    );

                    // Change the external data and pulse tx_start.
                    // The active frame must still send original_data.
                    tx_data  = 8'h3C;
                    tx_start = 1'b1;

                    seen_start_while_busy      = 1'b1;
                    seen_data_change_while_busy = 1'b1;

                    @(negedge clk);
                    tx_start = 1'b0;
                end
            join

            check_completion("request-while-busy");
        end
    endtask

    //============================================================
    // Minimum-gap back-to-back frames
    //
    // Start the second frame while tx_done is high and tx_busy
    // is low. The second request is accepted at the next edge.
    //============================================================

    task automatic test_back_to_back;
        logic [7:0] first_data;
        logic [7:0] second_data;
        begin
            first_data  = 8'hA5;
            second_data = 8'h01;

            $display("[%0t] Testing back-to-back frames", $time);

            start_frame(first_data);
            expect_frame_symbols(first_data, "back-to-back first frame");

            check(tx_done === 1'b1,
                  "First back-to-back frame must produce tx_done");

            check(tx_busy === 1'b0,
                  "TX must be ready when first frame completes");

            // We are currently at a falling edge during tx_done.
            tx_data  = second_data;
            tx_start = 1'b1;
            seen_back_to_back = 1'b1;

            // The second request is accepted at the next rising edge.
            @(negedge clk);

            tx_start = 1'b0;
            sample_accepted_data(second_data);

            check(tx_done === 1'b0,
                  "tx_done must clear when the next frame begins");

            check(tx_busy === 1'b1,
                  "Second back-to-back frame was not accepted");

            check(tx_serial === 1'b0,
                  "Second frame did not begin with a start bit");

            expect_frame_symbols(second_data, "back-to-back second frame");
            check_completion("back-to-back second frame");
        end
    endtask

    //============================================================
    // Reset in the middle of a frame
    //============================================================

    task automatic test_reset_while_busy;
        begin
            $display("[%0t] Testing reset while busy", $time);

            start_frame(8'h3C);

            // Move into the data portion of the frame.
            repeat (EXPECTED_CLKS_PER_BIT + 2)
                @(negedge clk);

            check(tx_busy === 1'b1,
                  "TX must be busy before mid-frame reset");

            seen_reset_while_busy = 1'b1;

            // rst_n is synchronous in the current DUT.
            rst_n = 1'b0;

            @(posedge clk);
            @(negedge clk);

            check(tx_serial === 1'b1,
                  "Reset must return the serial line to idle");

            check(tx_busy === 1'b0,
                  "Reset must clear tx_busy");

            check(tx_done === 1'b0,
                  "Reset must clear tx_done");

            rst_n = 1'b1;

            @(posedge clk);
            @(negedge clk);

            check(tx_serial === 1'b1,
                  "Serial line must remain idle after reset release");

            check(tx_busy === 1'b0,
                  "TX must remain idle after reset release");
        end
    endtask

    //============================================================
    // Portable coverage report
    //============================================================

    task automatic report_manual_coverage;
        begin
            $display("");
            $display("================ COVERAGE REPORT ================");
            $display("Accepted transactions       : %0d",
                     accepted_transactions);
            $display("Zero byte                   : %0b", seen_zero);
            $display("All-ones byte               : %0b", seen_all_ones);
            $display("Alternating byte            : %0b", seen_alternating);
            $display("Other byte                  : %0b", seen_other);
            $display("Parity bit 0                : %0b", seen_parity_zero);
            $display("Parity bit 1                : %0b", seen_parity_one);
            $display("Start attempted while busy  : %0b", seen_start_while_busy);
            $display("Data changed while busy     : %0b", seen_data_change_while_busy);
            $display("Back-to-back frames         : %0b", seen_back_to_back);
            $display("Reset while busy            : %0b", seen_reset_while_busy);
            $display("=================================================");

            // Turn missing coverage into test failures.
            check(seen_zero,
                  "Coverage missing: zero byte");

            check(seen_all_ones,
                  "Coverage missing: all-ones byte");

            check(seen_alternating,
                  "Coverage missing: alternating byte");

            check(seen_other,
                  "Coverage missing: ordinary byte");

            check(seen_parity_zero,
                  "Coverage missing: transmitted parity value 0");

            check(seen_parity_one,
                  "Coverage missing: transmitted parity value 1");

            check(seen_start_while_busy,
                  "Coverage missing: start request while busy");

            check(seen_data_change_while_busy,
                  "Coverage missing: tx_data changed while busy");

            check(seen_back_to_back,
                  "Coverage missing: back-to-back frames");

            check(seen_reset_while_busy,
                  "Coverage missing: reset while busy");
        end
    endtask

    //============================================================
    // Optional concurrent SystemVerilog assertions
    //
    // Enable these only with a simulator supporting SVA:
    // +define+ENABLE_SVA
    //============================================================

`ifdef ENABLE_SVA

    property p_idle_line_is_high;
        @(posedge clk)
        disable iff (!rst_n)
        !tx_busy |-> tx_serial;
    endproperty

    property p_done_means_not_busy;
        @(posedge clk)
        disable iff (!rst_n)
        tx_done |-> (!tx_busy && tx_serial);
    endproperty

    property p_done_is_one_clock;
        @(posedge clk)
        disable iff (!rst_n)
        tx_done |=> !tx_done;
    endproperty

    property p_accepted_request_sets_busy;
        @(posedge clk)
        disable iff (!rst_n)
        (tx_start && !tx_busy) |=> tx_busy;
    endproperty

    property p_outputs_are_known;
        @(posedge clk)
        disable iff (!rst_n)
        !$isunknown({tx_serial, tx_busy, tx_done});
    endproperty

    property p_reset_values;
        @(posedge clk)
        !rst_n |=> (tx_serial && !tx_busy && !tx_done);
    endproperty

    A_IDLE_HIGH:
        assert property (p_idle_line_is_high)
        else $error("SVA: serial line was low while idle");

    A_DONE_NOT_BUSY:
        assert property (p_done_means_not_busy)
        else $error("SVA: tx_done occurred while TX was busy");

    A_DONE_ONE_CLOCK:
        assert property (p_done_is_one_clock)
        else $error("SVA: tx_done lasted longer than one clock");

    A_ACCEPT_SETS_BUSY:
        assert property (p_accepted_request_sets_busy)
        else $error("SVA: accepted request did not set tx_busy");

    A_OUTPUTS_KNOWN:
        assert property (p_outputs_are_known)
        else $error("SVA: TX output contained X or Z");

    A_RESET_VALUES:
        assert property (p_reset_values)
        else $error("SVA: incorrect output values after reset");

    // Assertion coverage
    C_REQUEST_TO_DONE:
        cover property (
            @(posedge clk)
            disable iff (!rst_n)
            (tx_start && !tx_busy)
            ##1 tx_busy
            ##[1:$] tx_done
        );

    C_START_WHILE_BUSY:
        cover property (
            @(posedge clk)
            disable iff (!rst_n)
            tx_start && tx_busy
        );

    C_BACK_TO_BACK:
        cover property (
            @(posedge clk)
            disable iff (!rst_n)
            (tx_done && tx_start)
            ##1 tx_busy
        );

`endif

    //============================================================
    // Optional simulator-managed functional coverage
    //
    // Enable only if the simulator supports covergroups:
    // +define+ENABLE_COVERGROUPS
    //============================================================

`ifdef ENABLE_COVERGROUPS

    covergroup tx_functional_coverage @(posedge clk);
        option.per_instance = 1;

        accepted_data: coverpoint tx_data
            iff (rst_n && tx_start && !tx_busy) {
                bins zero         = {8'h00};
                bins all_ones     = {8'hFF};
                bins alternating[] = {8'h55, 8'hAA};
                bins walking_one[] = {
                    8'h01, 8'h02, 8'h04, 8'h08,
                    8'h10, 8'h20, 8'h40, 8'h80
                };
                bins other = default;
            }

        parity_value: coverpoint (^tx_data)
            iff (rst_n && tx_start && !tx_busy) {
                bins parity_zero = {1'b0};
                bins parity_one  = {1'b1};
            }

        start_while_busy: coverpoint (tx_start && tx_busy)
            iff (rst_n) {
                bins exercised = {1'b1};
                ignore_bins not_exercised = {1'b0};
            }

        data_parity_cross: cross accepted_data, parity_value;
    endgroup

    tx_functional_coverage tx_coverage;

    initial begin
        tx_coverage = new();
    end

`endif

    //============================================================
    // Main test sequence
    //============================================================

    initial begin
        $dumpfile("tx_tb.vcd");
        $dumpvars(0, tb_TX);

        checks                 = 0;
        errors                 = 0;
        accepted_transactions  = 0;
        previous_done          = 1'b0;

        rst_n                  = 1'b0;
        tx_start               = 1'b0;
        tx_data                = 8'h00;

        seen_zero                  = 1'b0;
        seen_all_ones              = 1'b0;
        seen_alternating           = 1'b0;
        seen_other                 = 1'b0;
        seen_parity_zero           = 1'b0;
        seen_parity_one            = 1'b0;
        seen_start_while_busy      = 1'b0;
        seen_data_change_while_busy = 1'b0;
        seen_back_to_back          = 1'b0;
        seen_reset_while_busy      = 1'b0;

        check(
            ((CLK_FREQ_HZ + (BAUD_RATE / 2)) / BAUD_RATE)
                == EXPECTED_CLKS_PER_BIT,
            "Testbench clock/baud configuration is not 10 clocks per bit"
        );

        reset_dut();

        run_frame(8'h00, "all-zero byte");
        run_frame(8'hFF, "all-one byte");
        run_frame(8'h55, "alternating byte");
        run_frame(8'h01, "parity-one byte");
        run_frame(8'h96, "bit-order byte");

        test_request_while_busy();
        test_back_to_back();
        test_reset_while_busy();

        // Confirm the TX recovers after a mid-frame reset.
        run_frame(8'h5A, "post-reset recovery");

        report_manual_coverage();

        $display("");
        $display("Total assertion checks: %0d", checks);
        $display("Total errors          : %0d", errors);

        if (errors == 0) begin
            $display("======================================");
            $display("        ALL TX TESTS PASSED");
            $display("======================================");
            $finish;
        end
        else begin
            $fatal(1, "TX verification failed with %0d errors", errors);
        end
    end

    // Simulation timeout prevents a broken DUT from running forever.
    initial begin
        repeat (100_000)
            @(posedge clk);

        $fatal(1, "Simulation timeout");
    end

endmodule